import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { QueryProviders } from "../providers/query-provider";
import SheetProvider from "../providers/sheet-provider";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });
import { dark, neobrutalism, shadesOfPurple } from '@clerk/themes';

export const metadata: Metadata = {
  title: "Welcome to SBI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
     appearance={{
      variables: { 
        colorPrimary: 'blue',
        colorNeutral: 'blue',
        colorDanger: 'red',
        colorShimmer: 'blue',
      }
    }}
    >
      <html lang="en">
        <body className={inter.className}>
          <QueryProviders>
            <SheetProvider/>
            <Sonner />
              {children}
             <Toaster/>
          </QueryProviders>
        </body>
      </html>
    </ClerkProvider>
  );
}
